<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>SME Summit 2019 - PDF Ticket</title>
  </head>
  <body style="font-family:Helvetica,Arial,sans-serif;">
    <table border="0" cellpadding="30" cellspacing="0" width="100%">
      <tr>
        <td
          align="center"
          valign="center"
          width="70px"
          style="border-bottom: 1px solid #5185eb;"
        >
          <img
            src="https://www.smesummit.id/images/logo/SMESummit_Logo100.png"
            alt="SME Summit Logo"
            style="width: 70px;background-color: #fff;padding: .5em;border-radius: 0.5em;border: 2px solid #5185eb;"
          />
        </td>
        <td valign="center" style="border-bottom: 1px solid #5185eb;">
          <h1>
            SME SUMMIT 2019
          </h1>
          <h2>
            DIGITAL TRANSFORMATION FOR NON-TECH COMPANY
          </h2>
          <span>
            Ballroom Ayana Hotel Midplaza, Jakarta, 25 April 2019
          </span>
        </td>
      </tr>
    </table>

    <br /><br />
    <div>
      Dear <?php print $u["name"]; ?>, <br /><br />
      Anda telah terdaftar di <b>smesummit.id</b> dengan detail berikut:
      <br /><br />
      <table border="0" cellpadding="0" cellspacing="0" width="100%">
        <tr>
          <td>Email</td>
          <td>:</td>
          <td><?php print $u["email"]; ?></td>
        </tr>
        <tr>
          <td>Nama</td>
          <td>:</td>
          <td><?php print $u["name"]; ?></td>
        </tr>
        <tr>
          <td>Perusahaan</td>
          <td>:</td>
          <td>
            <?php print $u["company_name"]; ?>
          </td>
        </tr>
        <tr>
          <td>Posisi</td>
          <td>:</td>
          <td><?php print $u["company_name"]; ?></td>
        </tr>
        <tr>
          <td>Telepon</td>
          <td>:</td>
          <td><?php print $u["phone"]; ?></td>
        </tr>
        <tr>
          <td>Kode Tiket</td>
          <td>:</td>
          <td><?php print $u["ticket_code"]; ?></td>
        </tr>
      </table>

      <br /><br />
      Berikut kami kirimkan QR Code sebagai tiket Anda untuk pendaftaran pada
      acara SME Summit 2019.
      <table border="0" cellpadding="0" cellspacing="0" width="100%">
        <tr>
          <td valign="top">
            <img src="data:image/png;base64,<?php print $qrCode; ?>" alt="" srcset=""/>
            <br>
            <img src="data:image/jpg;base64,<?php print $barCode; ?>" alt="" srcset=""/>
            <br>
          </td>
        </tr>
      </table>
    </div>

    <br /><br />

    Terima kasih,
    <br><br>
    Panitia SME Summit 2019
    <br><br><br><br>
    <small>
      This ticket is generated by smesummit.id on <?php print date("Y-m-d H:i:s"); ?>
    </small>
  </body>
</html>
